// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE7WOS9FCV9x_kMIb_E_UacaGYYyNHogE',
    appId: '1:103241477938:web:a52fb361382e691a47312b',
    messagingSenderId: '103241477938',
    projectId: 'pingme-141fe',
    authDomain: 'pingme-141fe.firebaseapp.com',
    storageBucket: 'pingme-141fe.firebasestorage.app',
    measurementId: 'G-YWJ0DEKTQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDADUG5VFzEIzoQdmX0WBFFTxZc60fCCO8',
    appId: '1:103241477938:android:b2ecc0787e04950547312b',
    messagingSenderId: '103241477938',
    projectId: 'pingme-141fe',
    storageBucket: 'pingme-141fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZNf1ES_Du7Cq9TT8r-Xr7C9k8gPCae3Y',
    appId: '1:103241477938:ios:a894226cf0c6b4d547312b',
    messagingSenderId: '103241477938',
    projectId: 'pingme-141fe',
    storageBucket: 'pingme-141fe.firebasestorage.app',
    iosClientId: '103241477938-qk1a05dca8fq4s1vfea2u2ufc6d17g4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZNf1ES_Du7Cq9TT8r-Xr7C9k8gPCae3Y',
    appId: '1:103241477938:ios:a894226cf0c6b4d547312b',
    messagingSenderId: '103241477938',
    projectId: 'pingme-141fe',
    storageBucket: 'pingme-141fe.firebasestorage.app',
    iosClientId: '103241477938-qk1a05dca8fq4s1vfea2u2ufc6d17g4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE7WOS9FCV9x_kMIb_E_UacaGYYyNHogE',
    appId: '1:103241477938:web:f1086588ae9f864847312b',
    messagingSenderId: '103241477938',
    projectId: 'pingme-141fe',
    authDomain: 'pingme-141fe.firebaseapp.com',
    storageBucket: 'pingme-141fe.firebasestorage.app',
    measurementId: 'G-LS0M7Q2G5Y',
  );
}
